name: CI Pipeline

on:
  push:
    branches:
      - lab3
  pull_request:
    branches:
      - lab3

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt

      - name: Run Linter
        run: |
          pip install flake8
          flake8 app_python/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 app_python/ --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

      - name: Run Tests
        run: python -m unittest app_python/tests.py

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Cache
        run: |
          docker build \
            --cache-from=${{ secrets.DOCKER_USERNAME }}/flask-app:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/flask-app:latest \
            -f app_python/Dockerfile app_python/

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
